### ISSUE TITLE
Error when creating an image style

### ISSUE THREAD

**Issue by korontari** [backdrop-contrib/imagemagick#1]
First of all thank you so much for working on this module. Very much awaited module by me at least. :) Some issues I have to report though.

When creating a new image style an error appears:

`Error: Call to undefined function conig_get() in imagemagick_advanced_imagemagick_arguments_alter() (line 75 of ../modules/imagemagick/imagemagick_advanced/imagemagick_advanced.module).`

Looks like it is just a typo (should be config_get instead). This prevents proper creation of image styles but easy to fix.

**Comment by a8w4** [comment]
yeah, confirmed - it block's also any changes to image styles - quite the showstopper!

**Comment by indigoxela** [comment]
@jenlampton you're probably awfully busy, but here's a [PR](https://github.com/backdrop-contrib/imagemagick/pull/5) that fixes the typo.

**Comment by jenlampton** [comment]
Thanks for fixing. I've merged the PR and will make a new release.
